name: 🐧 Linux Builds

on:
  workflow_call:

# Global Settings
env:
  BUILD_TYPE: Release
  BUILD_CONFIG_FNAME: GoodsackEngineConfig.h
  TEST_EXECUTABLE: GoodsackEngine_Test
  GEN_EXECUTABLE: GoodsackEngine_Gen

jobs:
# Linux Release Build
#
  build-linux:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Runtime and API
            run_tests: true
            artifact: false

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Package Cache
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: xorg-dev libglu1-mesa-dev libvulkan-dev libopenal1 libopenal-data libopenal-dev libpulse-dev ccache

    - name: Setup CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build (GoodsackEngine_Gen)
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target GoodsackEngine_Gen

    - name: Run GoodsackEngine_Gen
      run: ${{github.workspace}}/build/bin/${{env.GEN_EXECUTABLE}}

    - name: Build (all targets)
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Show configuration
      run: |
        cat ${{github.workspace}}/build/lib/gsk_generated/${{env.BUILD_CONFIG_FNAME}}

    - name: Setup Tests
      run: |
        ls -R
        chmod +x ${{github.workspace}}/build/bin/${{env.TEST_EXECUTABLE}}
        ldd ${{github.workspace}}/build/bin/${{env.TEST_EXECUTABLE}}

    - name: Run Tests
      if: ${{ matrix.run_tests }}
      run: ${{github.workspace}}/build/bin/${{env.TEST_EXECUTABLE}}