name: 📊 Static Analysis
on: [push, pull_request]

jobs:
  formatting-check:
    name: format check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'goodsack/gsk'
            exclude: '(thirdparty|__generated__)'
          - check: 'demo'
            exclude: '' # Nothing to exclude
      steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.10.1
        with:
          clang-format-version: '13'
          check-path: 'src'
