# using the following CI module:
# https://github.com/jidicula/clang-format-action

name: 📊 Static Analysis

on:
  workflow_call:

jobs:
  formatting-check:
    name: format check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'goodsack/gsk/gsk'
            exclude: '(__generated__)'
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '13'
          check-path: ${{matrix.path['check']}}
          exclude-regex: ${{matrix.path['exclude']}}
          fallback-style: 'LLVM'
