name: 💻 Windows Builds

on:
  workflow_call:

env:
  BUILD_TYPE: Release
  BUILD_CONFIG_FNAME: GoodsackEngineConfig.h
  TEST_EXECUTABLE: GoodsackEngine_Test

jobs:
  build-windows:
    runs-on: windows-latest
    name: Windows MSVC

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set up the MSVC environment variables
    - name: MSVC DevCmd
      uses: ilammy/msvc-dev-cmd@v1       # sets vcvars64 for the shell

    # Latest CMake (includes Ninja if we want it)
    - name: CMake
      uses: lukka/get-cmake@latest

      # grab baseline from vcpkg.json
    - name: Extract vcpkg baseline
      id: baseline
      shell: pwsh
      continue-on-error: true
      working-directory: ${{ github.workspace }}
      run: |
        $manifest   = Join-Path $env:GITHUB_WORKSPACE 'vcpkg.json'
        $baseline   = (Get-Content $manifest -Raw | ConvertFrom-Json).'builtin-baseline'
        "baseline=$baseline" | Out-File -Encoding utf8 -FilePath $env:GITHUB_OUTPUT
        echo $baseline
        echo $env:GITHUB_OUTPUT

    # vcpkg + binary caching
    - name: vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        runVcpkgInstall: true
        vcpkgJsonGlob: '**/vcpkg.json'

    # Configure with the *Visual Studio* generator
    - name: Configure
      run: >
        cmake -S . -B build
        -G "Visual Studio 17 2022"
        -A x64
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    # Build with MSBuild through CMake (multi-config needs --config)
    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    # Show generated config header
    - name: Show configuration
      run: type build\\${{ env.BUILD_CONFIG_FNAME }}

    # Run tests
    - name: Run Tests
      working-directory: ${{ github.workspace }}/build/output/bin/${{ env.BUILD_TYPE }}
      run: |
        ls
        ./${{ env.TEST_EXECUTABLE }}.exe